name: Build APK

# on:
#   push:
#     branches: [main, develop]
#   pull_request:
#     branches: [main]

# run-name: Build APK

on:
  # schedule:
  #   # Run every day at 20:00 UTC
  #   - cron: "0 20 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [debug, release]

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up JDK
        uses: actions/setup-java@main
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Gradle packages
        uses: actions/cache@main
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assemble${{ matrix.build_type == 'debug' && 'Debug' || 'Release' }}

      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: app-${{ matrix.build_type }}
          path: app/build/outputs/apk/${{ matrix.build_type }}/*.apk
